stages:
  - deploy

deploy_smart_bulb_bot:
  stage: deploy
  script:
    - env -u DOCKER_HOST docker compose build smart_bulb.bot
    - env -u DOCKER_HOST docker compose up -d --force-recreate --no-deps smart_bulb.bot
  only:
    refs:
      - master
