services:
  smart_bulb.bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_bulb.bot
    restart: always
    volumes:
      - ./sber_refresh_token:/usr/src/app/sber_refresh_token
    env_file:
      - .env
